behaviors:
  Builder:
    trainer_type: ppo
    hyperparameters:
      batch_size: 100
      buffer_size: 1000
      learning_rate: 1.0e-5
      beta: 1.0e-2
      epsilon: 0.1
      lambd: 0.99
      num_epoch: 3
      learning_rate_schedule: linear
      beta_schedule: constant
      epsilon_schedule: linear
    network_settings:
      normalize: false
      vis_encode_type: resnet
      hidden_units: 128
      num_layers: 1
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 3000000
    time_horizon: 64
    summary_freq: 10000
